- name: Hello world
  hosts: image-test
  gather_facts: no
  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 600

    - name: Gather facts
      setup:

    - name: Gather services facts
      service_facts:
  
    - name: Print hello world
      debug:
        msg: "Hello World"

